-- Contenido demo para la página "Nosotros"

INSERT INTO public.paginas_contenido (pagina, seccion, titulo, contenido, orden) VALUES
('nosotros', 'quienes_somos', '¿Quiénes Somos?',
'<p>Somos una empresa dedicada a brindar soluciones tecnológicas de alta calidad, especializada en la comercialización de equipos de cómputo, capacitación y asesoramiento para empresas tanto del sector público como privado. Con un enfoque centrado en la ética profesional, la responsabilidad y el trato humano, IYAYKU busca atender las diversas necesidades de sus clientes de manera eficiente. Además, la empresa apuesta por el desarrollo continuo de sus colaboradores, fomentando la lealtad, el trabajo en equipo y el compromiso con la sostenibilidad ambiental, asegurando así su rentabilidad y permanencia en el mercado.</p>', 1),
('nosotros', 'quienes_somos_img', NULL, '<img src="/Images/AcercaNosotros.png" alt="Acerca de Nosotros">', 2),
('nosotros', 'mision', 'Misión',
'<p>IYAYKU INNOVACIÓN TECNOLÓGICA tiene la misión de ofrecer servicios empresariales de calidad con calidez, ser especialistas en la comercialización de equipos de cómputo, capacitación y asesoría a empresas públicas y privadas, solucionando las diversas necesidades de los clientes, con ética profesional y responsabilidad. La empresa se enfoca en capacitar constantemente a sus colaboradores, promoviendo la lealtad y el trabajo en equipo para asegurar la rentabilidad de la empresa y la sostenibilidad ambiental.</p>', 3),
('nosotros', 'mision_img', NULL, '<img src="/Images/mision.png" alt="Mision">', 4),
('nosotros', 'vision', 'Visión',
'<p>Ser una empresa líder en innovación tecnológica, consultoría especializada y producción académica, reconocida por su excelencia, compromiso social y capacidad de adaptación, contribuyendo al fortalecimiento del ecosistema empresarial y educativo a nivel nacional e internacional.</p>', 5),
('nosotros', 'vision_img', NULL, '<img src="/Images/vision.png" alt="Visión">', 6),
('nosotros', 'footer', NULL, '<footer class="footer">\n  <div class="footer-col">\n    <h3>Dirección</h3>\n    <p>Dirección: Av. Amazonas y Colón, Quito – Ecuador</p>\n  </div>\n  <div class="footer-col">\n    <h3>Síguenos</h3>\n    <div class="footer-socials">\n      <a href="https://api.whatsapp.com/send?phone=593997000496&text=%C2%A1Hola%20Iyayku%20Innova%20Editores!%20me%20gustar%C3%ADa%20saber%20m%C3%A1s%20informaci%C3%B3n%20acerca%20de%20la%20asesor%C3%ADa%20y%20publicaci%C3%B3n%20de%20art%C3%ADculos%20cient%C3%ADficos.%20%E2%9C%8D%EF%B8%8F%F0%9F%93%8A%F0%9F%93%9D" target="_blank" rel="noopener noreferrer">\n        <img src="/svgs/whatsapp_black_logo_icon_147050.svg" alt="WhatsApp" />\n      </a>\n      <a href="https://www.facebook.com/Iyaykutec" target="_blank" rel="noopener noreferrer">\n        <img src="/svgs/facebook_black_logo_icon_147136.svg" alt="Facebook" />\n      </a>\n      <a href="https://www.instagram.com/iyaykutec" target="_blank" rel="noopener noreferrer">\n        <img src="/svgs/instagram_black_logo_icon_147122.svg" alt="Instagram" />\n      </a>\n    </div>\n  </div>\n  <div class="footer-col">\n    <h3>Información</h3>\n    <p>Email: iyayku@gmail.com</p>\n    <p>Teléfonos: 0995000484 · 0979369650 · 0997000496</p>\n  </div>\n</footer>', 99);
